CREATE DATABASE IF NOT EXISTS gadgets CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;USE gadgets;CREATE TABLE products(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(180) NOT NULL,category VARCHAR(100) NOT NULL,price DECIMAL(12,2) NOT NULL,icon VARCHAR(20) DEFAULT '📦',details TEXT,active TINYINT(1) DEFAULT 1,featured TINYINT(1) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);CREATE TABLE orders(id INT AUTO_INCREMENT PRIMARY KEY,order_no VARCHAR(60) UNIQUE NOT NULL,customer_name VARCHAR(150) NOT NULL,phone VARCHAR(40) NOT NULL,email VARCHAR(180) NOT NULL,address TEXT NOT NULL,payment_method VARCHAR(80) NOT NULL,total DECIMAL(12,2) NOT NULL,note TEXT,status VARCHAR(40) DEFAULT 'Pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);CREATE TABLE order_items(id INT AUTO_INCREMENT PRIMARY KEY,order_id INT NOT NULL,product_id INT,product_name VARCHAR(180) NOT NULL,qty INT NOT NULL,price DECIMAL(12,2) NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);CREATE TABLE agents(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,phone VARCHAR(40),email VARCHAR(180),active TINYINT(1) DEFAULT 1);CREATE TABLE quick_messages(id INT AUTO_INCREMENT PRIMARY KEY,message TEXT NOT NULL,sort_order INT DEFAULT 0,active TINYINT(1) DEFAULT 1);CREATE TABLE store_settings(setting_key VARCHAR(100) PRIMARY KEY,setting_value TEXT);INSERT INTO products(name,category,price,icon,details,featured) VALUES
('Apple MacBook Air 13','Laptops',129900,'💻','M3 · 8GB · 256GB SSD',1),
('Dell XPS 13','Laptops',145000,'💻','Core Ultra · 16GB · 512GB SSD',1),
('Lenovo Legion 5','Laptops',139900,'💻','Ryzen 7 · 16GB · RTX graphics',1),
('ASUS ROG G16','Laptops',179900,'💻','Core i9 · 16GB · RTX 4070',1),
('Custom Creator PC','Computers',165000,'🖥️','Ryzen 7 · 32GB · RTX 4070',1),
('Dell UltraSharp 27','Computers',59000,'🖥️','27-inch 4K IPS display',0),
('Logitech MX Keys','Accessories',12500,'⌨️','Wireless productivity keyboard',0),
('Razer DeathAdder V3','Accessories',8500,'🖱️','Ergonomic gaming mouse',0);
INSERT INTO quick_messages(message,sort_order) VALUES('Hi! How can I help you today?',1),('Tell me your budget and device type.',2),('I can compare products for you.',3);