let state={products:[],categories:[],orders:[],agents:[],settings:{},offers:[],reviews:[],banners:[],quick:[]};
const $=id=>document.getElementById(id);
async function api(action,data){const r=await fetch('../api/admin.php?action='+action,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});return r.json()}
async function load(){state=await api('all');$('productCount').textContent=state.products.length;$('categoryCount').textContent=state.categories.filter(x=>Number(x.active)).length;$('orderCount').textContent=state.orders.length;$('offerCount').textContent=state.offers.filter(x=>Number(x.active)).length;renderProducts();renderCategories();renderOrders();renderOffers();renderBanners();renderReviews();renderAgents();renderSettings();$('quick').value=state.quick.map(x=>x.message).join('\n')}
function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function renderProducts(){const q=($('productSearch').value||'').toLowerCase();$('productRows').innerHTML=state.products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(q)).slice(0,300).map(p=>'<tr><td><img class="thumb" src="'+esc(p.image_url)+'">'+esc(p.name)+'</td><td>'+esc(p.category)+'</td><td>৳'+Number(p.price).toLocaleString()+'</td><td><span class="pill '+(Number(p.active)?'live':'off')+'">'+(Number(p.active)?'Live':'Hidden')+'</span></td><td><button class="mini" onclick="editProduct('+p.id+')">Edit</button><button class="mini danger" onclick="removeProduct('+p.id+')">Delete</button></td></tr>').join('')||'<tr><td colspan="5">No products.</td></tr>'}
function renderCategories(){$('categoryList').innerHTML=state.categories.map(c=>'<div class="category-item"><div><b>'+esc(c.name)+'</b><small>Order '+c.sort_order+'</small></div><span><button class="mini" onclick="editCategory('+c.id+')">Edit</button><button class="mini danger" onclick="removeCategory('+c.id+')">Hide</button></span></div>').join('')}
function renderOrders(){$('orderRows').innerHTML=state.orders.map(o=>'<tr><td><b>'+esc(o.order_no)+'</b><small>'+esc(o.created_at)+'</small></td><td>'+esc(o.customer_name)+'<small>'+esc(o.phone)+'</small></td><td>৳'+Number(o.total).toLocaleString()+'</td><td>'+esc(o.payment_method)+'</td><td><select onchange="setOrderStatus('+o.id+',this.value)">'+['Pending','Confirmed','Processing','Shipped','Delivered','Cancelled'].map(s=>'<option '+(o.status===s?'selected':'')+'>'+s+'</option>').join('')+'</select></td></tr>').join('')||'<tr><td colspan="5">No orders.</td></tr>'}
function renderOffers(){$('offerList').innerHTML=state.offers.map(o=>'<article class="campaign"><span class="tag">'+esc(o.type)+'</span><h3>'+esc(o.title)+'</h3><p>'+esc(o.subtitle)+'</p><strong>'+esc(o.discount_text)+'</strong><div><button class="mini" onclick="editOffer('+o.id+')">Edit</button><button class="mini danger" onclick="removeOffer('+o.id+')">Delete</button></div></article>').join('')||'<p class="muted">No campaigns.</p>'}
function renderBanners(){$('bannerList').innerHTML=state.banners.map(b=>'<article class="campaign"><span class="tag">'+esc(b.position)+'</span><h3>'+esc(b.title)+'</h3><p>'+esc(b.subtitle)+'</p><div><button class="mini" onclick="editBanner('+b.id+')">Edit</button><button class="mini danger" onclick="removeBanner('+b.id+')">Delete</button></div></article>').join('')||'<p class="muted">No banners.</p>'}
function renderReviews(){$('reviewList').innerHTML=state.reviews.map(r=>'<article class="campaign"><span class="tag">'+('★'.repeat(Number(r.rating)))+'</span><h3>'+esc(r.name)+'</h3><p>'+esc(r.review)+'</p><div><button class="mini" onclick="editReview('+r.id+')">Edit</button><button class="mini danger" onclick="removeReview('+r.id+')">Delete</button></div></article>').join('')}
function renderAgents(){$('agentList').innerHTML=state.agents.map(a=>'<div class="category-item"><div><b>'+esc(a.name)+'</b><small>'+esc(a.phone)+' · '+esc(a.email)+'</small></div><span><button class="mini" onclick="editAgent('+a.id+')">Edit</button><button class="mini danger" onclick="removeAgent('+a.id+')">Remove</button></span></div>').join('')}
function renderSettings(){for(const [k,v] of Object.entries(state.settings)){const e=document.querySelector('[name="'+k+'"]');if(e)e.value=v}}
function openModal(title,html,submit){$('modalTitle').textContent=title;$('editor').innerHTML=html;$('modal').classList.add('open');$('editor').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const r=await api(submit,d);if(!r.success)return alert(r.error||'Save failed');closeModal();load()}}
function closeModal(){$('modal').classList.remove('open')}
const cats=()=>state.categories.filter(c=>Number(c.active)).map(c=>'<option>'+esc(c.name)+'</option>').join('');
function openProduct(p={}){openModal(p.id?'Edit product':'Add product',`<input type="hidden" name="id" value="${p.id||''}"><input name="name" required placeholder="Product name" value="${esc(p.name)}"><select name="category" required>${cats()}</select><input name="price" required type="number" value="${p.price||''}" placeholder="Price"><input name="image_url" placeholder="Image URL" value="${esc(p.image_url)}"><input name="icon" value="${esc(p.icon||'▣')}"><textarea name="details" placeholder="Product specifications">${esc(p.details)}</textarea><label><input type="checkbox" name="featured" ${Number(p.featured)?'checked':''}> Featured</label><label><input type="checkbox" name="active" ${p.id?(Number(p.active)?'checked':''):'checked'}> Visible</label><button>Save product</button>`, 'product')}
function editProduct(id){openProduct(state.products.find(x=>x.id==id)||{})}async function removeProduct(id){if(confirm('Delete this product?')){await api('delete_product',{id});load()}}
function openCategory(c={}){openModal(c.id?'Edit category':'Add category',`<input type="hidden" name="id" value="${c.id||''}"><input name="name" required value="${esc(c.name)}" placeholder="Category name"><input name="sort_order" type="number" value="${c.sort_order||0}" placeholder="Sort order"><label><input type="checkbox" name="active" ${c.id?(Number(c.active)?'checked':''):'checked'}> Visible</label><button>Save category</button>`,'category')}
function editCategory(id){openCategory(state.categories.find(x=>x.id==id)||{})}async function removeCategory(id){if(confirm('Hide this category?')){await api('delete_category',{id});load()}}
function openOffer(o={}){openModal(o.id?'Edit campaign':'Add campaign',`<input type="hidden" name="id" value="${o.id||''}"><input name="title" required value="${esc(o.title)}" placeholder="Title"><input name="subtitle" value="${esc(o.subtitle)}" placeholder="Subtitle"><input name="discount_text" value="${esc(o.discount_text)}" placeholder="Discount text"><input name="image_url" value="${esc(o.image_url)}" placeholder="Image URL"><input name="link_url" value="${esc(o.link_url)}" placeholder="Link URL"><select name="type"><option ${o.type==='happy-hour'?'selected':''}>happy-hour</option><option ${o.type!=='happy-hour'?'selected':''}>offer</option></select><input name="start_at" type="datetime-local" value="${o.start_at?o.start_at.replace(' ','T'):''}"><input name="end_at" type="datetime-local" value="${o.end_at?o.end_at.replace(' ','T'):''}"><input name="sort_order" type="number" value="${o.sort_order||0}"><label><input type="checkbox" name="active" ${o.id?(Number(o.active)?'checked':''):'checked'}> Active</label><button>Save campaign</button>`,'offer')}
function editOffer(id){openOffer(state.offers.find(x=>x.id==id)||{})}async function removeOffer(id){if(confirm('Delete campaign?')){await api('delete_offer',{id});load()}}
function openBanner(b={}){openModal(b.id?'Edit banner':'Add banner',`<input type="hidden" name="id" value="${b.id||''}"><input name="title" required value="${esc(b.title)}" placeholder="Banner title"><input name="subtitle" value="${esc(b.subtitle)}" placeholder="Subtitle"><input name="image_url" value="${esc(b.image_url)}" placeholder="Image URL"><input name="link_url" value="${esc(b.link_url)}" placeholder="Link URL"><select name="position"><option>hero</option><option>side</option><option>promo</option></select><input name="sort_order" type="number" value="${b.sort_order||0}"><label><input type="checkbox" name="active" ${b.id?(Number(b.active)?'checked':''):'checked'}> Active</label><button>Save banner</button>`,'banner')}
function editBanner(id){openBanner(state.banners.find(x=>x.id==id)||{})}async function removeBanner(id){if(confirm('Delete banner?')){await api('delete_banner',{id});load()}}
function openReview(r={}){openModal(r.id?'Edit review':'Add review',`<input type="hidden" name="id" value="${r.id||''}"><input name="name" required value="${esc(r.name)}" placeholder="Customer name"><select name="rating"><option ${Number(r.rating)===5?'selected':''}>5</option><option ${Number(r.rating)===4?'selected':''}>4</option><option ${Number(r.rating)===3?'selected':''}>3</option><option ${Number(r.rating)===2?'selected':''}>2</option><option>1</option></select><textarea name="review" required placeholder="Review">${esc(r.review)}</textarea><input name="sort_order" type="number" value="${r.sort_order||0}"><label><input type="checkbox" name="active" ${r.id?(Number(r.active)?'checked':''):'checked'}> Visible</label><button>Save review</button>`,'review')}
function editReview(id){openReview(state.reviews.find(x=>x.id==id)||{})}async function removeReview(id){if(confirm('Delete review?')){await api('delete_review',{id});load()}}
function openAgent(a={}){openModal(a.id?'Edit agent':'Add agent',`<input type="hidden" name="id" value="${a.id||''}"><input name="name" required value="${esc(a.name)}" placeholder="Agent name"><input name="phone" value="${esc(a.phone)}" placeholder="Phone"><input name="email" value="${esc(a.email)}" placeholder="Email"><input name="whatsapp" value="${esc(a.whatsapp)}" placeholder="WhatsApp URL"><input name="messenger" value="${esc(a.messenger)}" placeholder="Messenger URL"><label><input type="checkbox" name="active" ${a.id?(Number(a.active)?'checked':''):'checked'}> Active</label><button>Save agent</button>`,'agent')}
function editAgent(id){openAgent(state.agents.find(x=>x.id==id)||{})}async function removeAgent(id){if(confirm('Remove agent?')){await api('delete_agent',{id});load()}}
async function setOrderStatus(id,status){await api('order_status',{id,status});load()}
async function saveQuick(){const r=await api('quick',{messages:$('quick').value.split('\n').map(x=>x.trim()).filter(Boolean)});alert(r.success?'Saved':'Save failed')}
$('settingsForm').onsubmit=async e=>{e.preventDefault();const r=await api('settings',Object.fromEntries(new FormData(e.target)));alert(r.success?'Settings saved':'Save failed');load()};
load();