<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gadgets — Control Room</title><link rel="stylesheet" href="admin.css"></head><body>
<aside><div class="brand">GADGETS<span>.</span><small>CONTROL ROOM</small></div><nav><a href="#dashboard">Overview</a><a href="#products">Products</a><a href="#categories">Categories</a><a href="#offers">Offers & Happy Hour</a><a href="#banners">Hero & Banners</a><a href="#orders">Orders</a><a href="#reviews">Reviews</a><a href="#chatbot">AI Chatbot</a><a href="#agents">Agents</a><a href="#settings">Store & Social</a></nav></aside>
<main><header><div><div class="eyebrow">GADGETS / ADMIN</div><h1>Store control room</h1><p>Products, categories, campaigns, chatbot, agents, reviews and storefront settings — all editable here.</p></div><a class="viewstore" href="../index.html">View store ↗</a></header>
<section id="dashboard" class="stats"><div><span>Products</span><b id="productCount">0</b></div><div><span>Categories</span><b id="categoryCount">0</b></div><div><span>Orders</span><b id="orderCount">0</b></div><div><span>Live offers</span><b id="offerCount">0</b></div></section>
<section id="products" class="panel"><div class="panelhead"><div><small>CATALOG</small><h2>Products</h2></div><button onclick="openProduct()">+ Add product</button></div><input class="table-search" id="productSearch" oninput="renderProducts()" placeholder="Search products..."><div class="tablewrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody id="productRows"></tbody></table></div></section>
<section id="categories" class="panel"><div class="panelhead"><div><small>NAVIGATION</small><h2>Categories</h2></div><button onclick="openCategory()">+ Add category</button></div><div id="categoryList" class="category-admin"></div></section>
<section id="offers" class="panel"><div class="panelhead"><div><small>CAMPAIGNS</small><h2>Offers & Happy Hour</h2></div><button onclick="openOffer()">+ Add campaign</button></div><div id="offerList" class="campaign-grid"></div></section>
<section id="banners" class="panel"><div class="panelhead"><div><small>VISUALS</small><h2>Hero & promotional banners</h2></div><button onclick="openBanner()">+ Add banner</button></div><div id="bannerList" class="campaign-grid"></div></section>
<section id="orders" class="panel"><div class="panelhead"><div><small>SALES</small><h2>Orders</h2></div></div><div class="tablewrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th></tr></thead><tbody id="orderRows"></tbody></table></div></section>
<section id="reviews" class="panel"><div class="panelhead"><div><small>SOCIAL PROOF</small><h2>Customer reviews</h2></div><button onclick="openReview()">+ Add review</button></div><div id="reviewList" class="campaign-grid"></div></section>
<section id="chatbot" class="panel"><div class="panelhead"><div><small>AI SUPPORT</small><h2>Quick messages</h2></div><button onclick="saveQuick()">Save</button></div><p class="muted">One message per line. The assistant supports English, বাংলা and Banglish product conversations.</p><textarea id="quick" rows="7"></textarea></section>
<section id="agents" class="panel"><div class="panelhead"><div><small>HUMAN SUPPORT</small><h2>Contact agents</h2></div><button onclick="openAgent()">+ Add agent</button></div><div id="agentList" class="agent-grid"></div></section>
<section id="settings" class="panel"><div class="panelhead"><div><small>BRAND CONTROL</small><h2>Store, support & social</h2></div></div><form id="settingsForm" class="settingsgrid"><input name="store_name" placeholder="Store name"><input name="support_email" placeholder="Support email"><input name="support_phone" placeholder="Support phone"><input name="store_address" placeholder="Store address"><input name="delivery_info" placeholder="Delivery information"><input name="facebook" placeholder="Facebook URL"><input name="instagram" placeholder="Instagram URL"><input name="youtube" placeholder="YouTube URL"><input name="whatsapp" placeholder="WhatsApp URL"><button>Save settings</button></form></section>
</main><div id="modal" class="modal"><div class="modalbox"><button class="close" onclick="closeModal()">×</button><h2 id="modalTitle"></h2><form id="editor"></form></div></div><script src="admin.js"></script></body></html>