<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gadgets Control Room</title><link rel="stylesheet" href="admin.css"></head><body>
<aside><div class="brand">GADGETS<span>.</span><small>CONTROL ROOM</small></div><nav><a href="#dashboard">Dashboard</a><a href="#products">Products</a><a href="#categories">Categories</a><a href="#orders">Orders</a><a href="#chatbot">Chatbot</a><a href="#agents">Agents</a><a href="#settings">Store & Social</a></nav></aside>
<main><header><div><h1>Store management</h1><p>Everything shown on the storefront can be managed here.</p></div></header>
<section id="dashboard" class="stats"><div><span>Products</span><b id="productCount">0</b></div><div><span>Categories</span><b id="categoryCount">0</b></div><div><span>Orders</span><b id="orderCount">0</b></div><div><span>Agents</span><b id="agentCount">0</b></div></section>
<section id="products" class="panel"><div class="panelhead"><div><small>CATALOG</small><h2>Products</h2></div><button onclick="openProduct()">+ Add product</button></div><div class="tablewrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Status</th><th></th></tr></thead><tbody id="productRows"></tbody></table></div></section>
<section id="categories" class="panel"><div class="panelhead"><div><small>SHOP NAVIGATION</small><h2>Categories</h2></div><button onclick="addCategory()">+ Add category</button></div><div id="categoryList" class="category-admin"></div></section>
<section id="orders" class="panel"><div class="panelhead"><div><small>SALES</small><h2>Recent orders</h2></div></div><div class="tablewrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody id="orderRows"></tbody></table></div></section>
<section id="chatbot" class="panel"><div class="panelhead"><div><small>CUSTOMER SUPPORT</small><h2>Chatbot quick messages</h2></div></div><textarea id="quick" rows="6"></textarea><button onclick="saveQuick()">Save quick messages</button></section>
<section id="agents" class="panel"><div class="panelhead"><div><small>HUMAN SUPPORT</small><h2>Contact agents</h2></div><button onclick="openAgent()">+ Add agent</button></div><div id="agentList" class="agent-grid"></div></section>
<section id="settings" class="panel"><div class="panelhead"><div><small>BRAND CONTROL</small><h2>Store & social</h2></div></div><form id="settingsForm" class="settingsgrid"><input name="facebook" placeholder="Facebook URL"><input name="instagram" placeholder="Instagram URL"><input name="youtube" placeholder="YouTube URL"><input name="whatsapp" placeholder="WhatsApp URL"><input name="store_name" placeholder="Store name"><input name="support_email" placeholder="Support email"><button>Save settings</button></form></section>
</main>
<div id="modal" class="modal"><div class="modalbox"><button class="close" onclick="closeModal()">×</button><h2 id="modalTitle"></h2><form id="editor"></form></div></div>
<script src="admin.js"></script></body></html>