<?php header('Content-Type: application/json');try{$c=require __DIR__.'/config.php';$p=new PDO("mysql:host={$c['db_host']};dbname={$c['db_name']};charset=utf8mb4",$c['db_user'],$c['db_pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$a=$_GET['action']??'stats';$d=json_decode(file_get_contents('php://input'),true)??[];
if($a==='all'){echo json_encode(['products'=>$p->query("SELECT id,name,category,price,image_url,icon,details,active,featured FROM products ORDER BY featured DESC,id DESC")->fetchAll(PDO::FETCH_ASSOC),'categories'=>$p->query("SELECT id,name FROM categories WHERE active=1 ORDER BY sort_order,id")->fetchAll(PDO::FETCH_ASSOC),'orders'=>$p->query("SELECT order_no,customer_name,total,status FROM orders ORDER BY id DESC LIMIT 50")->fetchAll(PDO::FETCH_ASSOC),'agents'=>$p->query("SELECT id,name,phone,email,whatsapp,messenger,active FROM agents ORDER BY id DESC")->fetchAll(PDO::FETCH_ASSOC),'quick'=>$p->query("SELECT message FROM quick_messages WHERE active=1 ORDER BY sort_order")->fetchAll(PDO::FETCH_COLUMN),'settings'=>array_column($p->query("SELECT setting_key,setting_value FROM store_settings")->fetchAll(PDO::FETCH_ASSOC),'setting_value','setting_key')]);exit;}
if($a==='stats'){echo json_encode(['products'=>(int)$p->query("SELECT COUNT(*) FROM products")->fetchColumn(),'orders'=>(int)$p->query("SELECT COUNT(*) FROM orders")->fetchColumn(),'agents'=>(int)$p->query("SELECT COUNT(*) FROM agents WHERE active=1")->fetchColumn()]);exit;}
if($a==='quick'){if($_SERVER['REQUEST_METHOD']==='GET'){echo json_encode(['messages'=>$p->query("SELECT message FROM quick_messages WHERE active=1 ORDER BY sort_order")->fetchAll(PDO::FETCH_COLUMN)]);exit;}$p->exec("DELETE FROM quick_messages");$s=$p->prepare("INSERT INTO quick_messages(message,sort_order,active) VALUES(?,?,1)");foreach(($d['messages']??[]) as $i=>$m)$s->execute([$m,$i]);echo json_encode(['success'=>true]);exit;}
if($a==='product'){$id=(int)($d['id']??0);if($id){$s=$p->prepare("UPDATE products SET name=?,category=?,price=?,image_url=?,icon=?,details=?,featured=?,active=? WHERE id=?");$s->execute([$d['name'],$d['category'],$d['price'],$d['image_url']??'',$d['icon']??'▣',$d['details']??'',$d['featured']??0,$d['active']??1,$id]);}else{$s=$p->prepare("INSERT INTO products(name,category,price,image_url,icon,details,featured,active) VALUES(?,?,?,?,?,?,?,?)");$s->execute([$d['name'],$d['category'],$d['price'],$d['image_url']??'',$d['icon']??'▣',$d['details']??'',$d['featured']??0,$d['active']??1]);}echo json_encode(['success'=>true]);exit;}
if($a==='delete_product'){$s=$p->prepare("DELETE FROM products WHERE id=?");$s->execute([(int)$d['id']]);echo json_encode(['success'=>true]);exit;}
if($a==='category'){$s=$p->prepare("INSERT INTO categories(name) VALUES(?)");$s->execute([trim($d['name'])]);echo json_encode(['success'=>true]);exit;}
if($a==='delete_category'){$s=$p->prepare("DELETE FROM categories WHERE id=?");$s->execute([(int)$d['id']]);echo json_encode(['success'=>true]);exit;}
if($a==='agent'){$s=$p->prepare("INSERT INTO agents(name,phone,email,whatsapp,messenger) VALUES(?,?,?,?,?)");$s->execute([$d['name'],$d['phone']??'',$d['email']??'',$d['whatsapp']??'',$d['messenger']??'']);echo json_encode(['success'=>true]);exit;}
if($a==='delete_agent'){$s=$p->prepare("UPDATE agents SET active=0 WHERE id=?");$s->execute([(int)$d['id']]);echo json_encode(['success'=>true]);exit;}
if($a==='settings'){foreach($d as $k=>$v){$s=$p->prepare("INSERT INTO store_settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)");$s->execute([$k,$v]);}echo json_encode(['success'=>true]);exit;}
throw new Exception('Unknown action');}catch(Throwable $e){http_response_code(400);echo json_encode(['success'=>false,'error'=>$e->getMessage()]);}